// <auto-generated />
using System;
using IvA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IvA.Migrations.ArbeitsPaket
{
    [DbContext(typeof(ArbeitsPaketContext))]
    partial class ArbeitsPaketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IvA.Models.ArbeitsPaket", b =>
                {
                    b.Property<int>("ArbeitsPaketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Frist")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mitglieder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArbeitsPaketId");

                    b.ToTable("ArbeitsPaket");
                });
#pragma warning restore 612, 618
        }
    }
}
